@startuml
start

:Менеджер готелю;
:Запит на бронювання;
if (Наявність вільних номерів?) then (так)
    :Створення бронювання;
    :Отримання підтвердження бронювання;
else (ні)
    :Відмова у бронюванні;
endif

:Запит на заселення;
if (Бронювання підтверджено?) then (так)
    :Заселення;
    :Отримання підтвердження заселення;
else (ні)
    :Відмова у заселенні;
endif

:Запит на виселення;
:Виселення;
:Отримання підтвердження виселення;

stop
@enduml
