@startuml
class Студент {
    - ПІБ: String
    - номер_заліковки: String
    - курс: int
    - спеціальність: String
    + отриматиІнформацію(): String
    + зареєструватисяНаДисципліну(дисципліна: Дисципліна)
}

class Викладач {
    - ПІБ: String
    - кафедра: String
    - посада: String
    + додатиОцінку(студент: Студент, дисципліна: Дисципліна, оцінка: int)
    + отриматиІнформацію(): String
}

class Дисципліна {
    - назва: String
    - код: String
    - кредити: int
    + отриматиІнформацію(): String
}

class ПроходженняДисциплін {
    - студент: Студент
    - дисципліна: Дисципліна
    - викладач: Викладач
    - оцінка: int
    + отриматиДеталі(): String
}

Студент -- ПроходженняДисциплін : "проходить"
Викладач -- ПроходженняДисциплін : "оцінює"
Дисципліна -- ПроходженняДисциплін : "включає"
@enduml
