@startuml
object Клієнт
object КоллЦентр

Клієнт -- КоллЦентр : Запит на інформацію (1)
КоллЦентр -- Клієнт : Відповідь на запит (2)

Клієнт -- КоллЦентр : Подати скаргу (3)
КоллЦентр -- Клієнт : Підтвердження отримання скарги (4)

Клієнт -- КоллЦентр : Запит статусу скарги (5)
КоллЦентр -- Клієнт : Статус скарги (6)

Клієнт -- КоллЦентр : Завершити дзвінок (7)

@enduml