@startuml
[*] --> Лід

Лід --> Вода : Підвищення температури
Вода --> Пар : Підвищення температури
Вода --> Лід : Зниження температури
Пар --> Вода : Зниження температури
Пар --> Лід : Конденсація

@enduml