@startuml
:Бібліотекар: as Librarian
:Користувач бібліотеки: as User

Librarian --> (Додати нову книжку в бібліотеку)
User --> (Запит про наявність книжки)
Librarian --> (Реєстрація отримання книжки)
User --> (Реєстрація отримання книжки)
Librarian --> (Реєстрація повернення книжки)
User --> (Реєстрація повернення книжки)

@enduml
